import type { Edge, Node } from '@xyflow/react';

import type { PlaygroundNodeData } from './types';

const MAIN_RUN_ID = 'playground-test-main';
const BRANCH_RUN_ID = 'playground-test-branch';
const SLA_RUN_ID = 'playground-test-sla';

export const playgroundDemoNodes: Array<Node<PlaygroundNodeData>> = [
  {
    id: 'demo-datasource',
    type: 'playground',
    position: { x: 0, y: 80 },
    data: {
      label: 'Data Source',
      description: '주문, 배송, 판매자, 리뷰 데이터가 분석 세션에 연결되었습니다.',
      kind: 'datasource',
      status: 'success',
      nodeSequence: 0,
      parentNodeId: null,
      agentName: 'datasource',
    },
  },
  {
    id: 'demo-sql',
    type: 'playground',
    position: { x: 460, y: 80 },
    data: {
      label: 'SQL Agent',
      description: '주문·배송·리뷰 데이터를 order_id 기준으로 결합하고 배송 소요일을 계산했습니다.',
      kind: 'sql-agent',
      status: 'success',
      runId: `${MAIN_RUN_ID}:sql`,
      nodeSequence: 1,
      parentNodeId: 'demo-datasource',
      agentName: 'sql_agent',
      queryBadges: [{
        label: '원본 쿼리',
        text: '배송 지연이 고객 리뷰 점수에 미치는 영향을 분석하고 개선 우선순위를 알려줘.',
        flowNodeId: 'demo-insight',
      }],
    },
  },
  {
    id: 'demo-eda',
    type: 'playground',
    position: { x: 920, y: 80 },
    data: {
      label: 'EDA Agent',
      description: '배송 지연이 길어질수록 리뷰 평점이 낮아지는 패턴과 판매자별 편차를 확인했습니다.',
      kind: 'EDA-agent',
      status: 'success',
      runId: `${MAIN_RUN_ID}:eda`,
      nodeSequence: 2,
      parentNodeId: 'demo-sql',
      agentName: 'eda_agent',
    },
  },
  {
    id: 'demo-analysis',
    type: 'playground',
    position: { x: 1380, y: 80 },
    data: {
      label: 'Analysis Agent',
      description: '카테고리와 지역 효과를 통제한 뒤에도 배송 지연과 평점 하락의 연관성이 유지되었습니다.',
      kind: 'analysis-agent',
      status: 'success',
      runId: `${MAIN_RUN_ID}:analysis`,
      nodeSequence: 3,
      parentNodeId: 'demo-eda',
      agentName: 'analysis_agent',
    },
  },
  {
    id: 'demo-insight',
    type: 'playground',
    position: { x: 1840, y: 80 },
    selected: true,
    data: {
      label: 'Insight Agent',
      description: '판매자별 개선 우선순위와 예상 고객 경험 효과를 정리하고 있습니다.',
      kind: 'insight-agent',
      status: 'running',
      runId: `${MAIN_RUN_ID}:insight`,
      nodeSequence: 4,
      parentNodeId: 'demo-analysis',
      agentName: 'insight_agent',
    },
  },
  {
    id: 'demo-sla-eda',
    type: 'playground',
    position: { x: 920, y: -180 },
    data: {
      label: 'EDA Agent',
      description: '판매자별 SLA 초과율과 출고 지연 분포를 비교해 반복 지연 판매자 그룹을 찾았습니다.',
      kind: 'EDA-agent',
      status: 'success',
      runId: `${SLA_RUN_ID}:eda`,
      nodeSequence: 2,
      parentNodeId: 'demo-sql',
      agentName: 'eda_agent',
      queryBadges: [{
        label: '판매자 분석',
        text: '판매자별 SLA 준수율을 비교하고 반복적으로 배송이 지연되는 그룹을 찾아줘.',
        flowNodeId: 'demo-sla-insight',
      }],
    },
  },
  {
    id: 'demo-sla-analysis',
    type: 'playground',
    position: { x: 1380, y: -180 },
    data: {
      label: 'Analysis Agent',
      description: '주문량과 상품 구성을 보정해도 일부 판매자의 SLA 초과 위험이 유의하게 높았습니다.',
      kind: 'analysis-agent',
      status: 'success',
      runId: `${SLA_RUN_ID}:analysis`,
      nodeSequence: 3,
      parentNodeId: 'demo-sla-eda',
      agentName: 'analysis_agent',
    },
  },
  {
    id: 'demo-sla-insight',
    type: 'playground',
    position: { x: 1840, y: -180 },
    data: {
      label: 'Insight Agent',
      description: 'SLA 개선 효과가 큰 판매자군과 모니터링할 핵심 운영 지표를 도출했습니다.',
      kind: 'insight-agent',
      status: 'success',
      runId: `${SLA_RUN_ID}:insight`,
      nodeSequence: 4,
      parentNodeId: 'demo-sla-analysis',
      agentName: 'insight_agent',
    },
  },
  {
    id: 'demo-branch-analysis',
    type: 'playground',
    position: { x: 1380, y: 340 },
    data: {
      label: 'Analysis Agent',
      description: '리뷰 작성 시점이 확정된 주문만 분리해 장기 지연 중심의 추가 검정을 완료했습니다.',
      kind: 'analysis-agent',
      status: 'success',
      runId: `${BRANCH_RUN_ID}:analysis`,
      nodeSequence: 3,
      parentNodeId: 'demo-eda',
      agentName: 'analysis_agent',
      queryBadges: [{
        label: '추가 분석',
        text: '리뷰 작성 시점이 명확한 주문만 사용해 장기 배송 지연의 영향을 다시 검증해줘.',
        flowNodeId: 'demo-branch-insight',
      }],
    },
  },
  {
    id: 'demo-branch-insight',
    type: 'playground',
    position: { x: 1840, y: 340 },
    data: {
      label: 'Insight Agent',
      description: '장기 지연 주문은 평점 하락 폭이 더 컸으며, 집중 관리 대상 판매자를 식별했습니다.',
      kind: 'insight-agent',
      status: 'success',
      runId: `${BRANCH_RUN_ID}:insight`,
      nodeSequence: 4,
      parentNodeId: 'demo-branch-analysis',
      agentName: 'insight_agent',
    },
  },
];

export const playgroundDemoEdges: Edge[] = [
  {
    id: 'demo-edge-datasource-sql',
    source: 'demo-datasource',
    target: 'demo-sql',
    type: 'playground',
    selectable: false,
    data: { flowState: 'idle' },
  },
  {
    id: 'demo-edge-sql-eda',
    source: 'demo-sql',
    target: 'demo-eda',
    type: 'playground',
    selectable: false,
    data: { flowState: 'idle' },
  },
  {
    id: 'demo-edge-eda-analysis',
    source: 'demo-eda',
    target: 'demo-analysis',
    type: 'playground',
    selectable: false,
    data: { flowState: 'idle' },
  },
  {
    id: 'demo-edge-analysis-insight',
    source: 'demo-analysis',
    target: 'demo-insight',
    type: 'playground',
    selectable: false,
    data: { flowState: 'idle' },
  },
  {
    id: 'demo-edge-sql-sla-eda',
    source: 'demo-sql',
    target: 'demo-sla-eda',
    type: 'playground',
    selectable: false,
    data: { flowState: 'idle' },
  },
  {
    id: 'demo-edge-sla-eda-analysis',
    source: 'demo-sla-eda',
    target: 'demo-sla-analysis',
    type: 'playground',
    selectable: false,
    data: { flowState: 'idle' },
  },
  {
    id: 'demo-edge-sla-analysis-insight',
    source: 'demo-sla-analysis',
    target: 'demo-sla-insight',
    type: 'playground',
    selectable: false,
    data: { flowState: 'idle' },
  },
  {
    id: 'demo-edge-eda-branch-analysis',
    source: 'demo-eda',
    target: 'demo-branch-analysis',
    type: 'playground',
    selectable: false,
    data: { flowState: 'idle' },
  },
  {
    id: 'demo-edge-branch-analysis-insight',
    source: 'demo-branch-analysis',
    target: 'demo-branch-insight',
    type: 'playground',
    selectable: false,
    data: { flowState: 'idle' },
  },
];

export const playgroundDemoGraph = {
  nodes: playgroundDemoNodes,
  edges: playgroundDemoEdges,
};
